name: Copilot Review Setup Guide

on:
  pull_request:
    types: [opened]

jobs:
  copilot-review-info:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    
    steps:
      - name: Add Copilot Review Instructions
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.COPILOT_REVIEW }}
          script: |
            const prNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            // Check if this is the first comment to avoid spamming
            const comments = await github.rest.issues.listComments({
              owner,
              repo,
              issue_number: prNumber
            });
            
            const hasCopilotComment = comments.data.some(comment => 
              comment.body.includes('GitHub Copilot Code Review Setup')
            );
            
            if (!hasCopilotComment) {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: prNumber,
                body: `## 🤖 GitHub Copilot Code Review Setup
                
            **Note:** GitHub Copilot cannot be requested as a reviewer programmatically. To enable automatic Copilot reviews for this repository:

            ### Option 1: Configure Repository Rules (Recommended)
            1. Go to **Settings** → **Rules** → **Rulesets**
            2. Create a new branch ruleset
            3. Under "Branch rules," select **Require a pull request before merging**
            4. Enable **Request pull request review from Copilot**

            ### Option 2: Manual Review Request
            - Click the **Reviewers** section in this PR
            - Select **Copilot** from the dropdown menu

            ### Requirements
            - Copilot Pro or Copilot Pro+ subscription for individual repos
            - Repository or organization owner access for configuration

            Once configured, Copilot will automatically review all new PRs (not drafts).

            [Learn more about Copilot code review](https://docs.github.com/en/copilot/using-github-copilot/code-review/configuring-automatic-code-review-by-copilot)`
              });
            }