name: Copilot Review Setup Guide

on:
  pull_request:
    types: [opened]

jobs:
  copilot-review-info:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    
    steps:
      - name: Add Copilot Review Instructions
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.COPILOT_REVIEW }}
          script: |
            const prNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            // Check if this is the first comment to avoid spamming
            const comments = await github.rest.issues.listComments({
              owner,
              repo,
              issue_number: prNumber
            });
            
            const hasCopilotComment = comments.data.some(comment => 
              comment.body.includes('GitHub Copilot Code Review Setup')
            );
            
            if (!hasCopilotComment) {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: prNumber,
                body: `## 🤖 GitHub Copilot Code Review Setup